name: Upload Built files

on:
  push:
    branches:
      - main

jobs:
  upload:
    name: Build and Upload files on Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build && pnpm run pack
      - name: Uploading Chrome Browser Extension
        uses: actions/upload-artifact@v4
        with:
          name: chrome
          path: extension.crx
      - name: Uploading Firefox Browser Extension
        uses: actions/upload-artifact@v4
        with:
          name: firefox
          path: extension.xpi
      - name: Uploading Edge, Opera and other Browser Extension (except Safari)
        uses: actions/upload-artifact@v4
        with:
          name: other
          path: extension.zip
